### ISSUE TITLE
List of possible issues with string parsing in v7

### ISSUE THREAD

**Issue by lipchev** [danm-de/Fractions#56]
Here are the summary of the tests that are failing in the current code base:

1. Parsing_a_fraction_from_a_long_decimal_string_with_specific_number_style (23 tests) 
- Should_not_work_with_groups_in_the_middle("123456789987654321.,123456789987654321")
- Should_not_work_with_groups_in_the_middle("123456789987654321.123456789,987654321")
- Should_return_the_expected_value_when_the_string_is_valid("1234,56789987654321.-",Any,)  // all strings with the +/- sign on the right side
- Should_return_the_expected_value_when_the_string_is_valid(" (.1) ",Any,) // all strings with "(..)" as negative pattern
2. Same issues are repeated with the scientific notation
3. All currency formats are affected as well
4. When parsing a string with a culture where the symbols are not the standard length (e.g. having "_minus_" instead of "-" for the negative sign).

When parsing a string with the sign / currency symbol to the right side, the results are incorrect due to the fact that the symbols to the right do not contribute to the number of decimals in the denominator:

```
The_result_should_be_minus_7_over_2("3,5-") Failed: Expected object to be equal to -7/2, but found -7/20.
Expected object to be equal to -7/2, but found -7/20.
   at FluentAssertions.Execution.LateBoundTestFramework.Throw(String message)
   at FluentAssertions.Execution.AssertionScope.FailWith(Func`1 failReasonFunc)
   at FluentAssertions.Numeric.ComparableTypeAssertions`2.Be(T expected, String because, Object[] becauseArgs)
   at Fractions.Tests.FractionSpecs.FromString.When_creating_a_fraction_from_minus_3_5_with_German_culture.The_result_should_be_minus_7_over_2(String value) in C:\Users\galin\source\repos\Fractions-fork\tests\Fractions.Tests\FractionSpecs\FromString\Method_FromString.cs:line 142
```

A PR is coming in a bit..

**Comment by danm-de** [comment]
Oh. I've added a 7.x branch: https://github.com/danm-de/Fractions/tree/release/7.x.x

**Comment by lipchev** [comment]
Should I create two PRs or just one for 7.x.x?

**Comment by danm-de** [comment]
> Should I create two PRs or just one for 7.x.x?

A single pull-request is cool. I can merge this into the master later.

**Comment by danm-de** [comment]
Version 7.7.1 with your changes is released. Thank you very much.
