### ISSUE TITLE
Possible OverflowException in Fraction.FromDoubleRounded

### ISSUE THREAD

**Issue by lipchev** [danm-de/Fractions#83]
This is a pretty extreme example (it's a small niche of values for which this could happen) but still - here's an example for which the `Fraction.FromDoubleRounded(double, bool)` is throwing an exception:

`Fraction.FromDoubleRounded(1.0 / (double.MaxValue - 100))`

> "BigInteger cannot represent infinity."

```
   at System.Numerics.BigInteger..ctor(Double value)
   at Fractions.Fraction.FromDoubleRounded(Double value, Boolean reduceTerms) Fraction.ConvertFromDouble.cs:line 213
   at Fractions.Fraction.FromDoubleRounded(Double value) in Fraction.ConvertFromDouble.cs:line 142
```

**Comment by danm-de** [comment]
Thanks, I hope I'll be able to check it out by the end of the week.
